project_id = "iycukvmyvphufsdhlzmj"

[functions.send-telegram-photo]
verify_jwt = false

[functions.submit-review]
verify_jwt = false

[functions.send-telegram]
verify_jwt = false

[functions.chat-bot]
verify_jwt = false

[functions.seo-prerender]
verify_jwt = false
