// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iycukvmyvphufsdhlzmj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5Y3Vrdm15dnBodWZzZGhsem1qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk5MTAzMDYsImV4cCI6MjA4NTQ4NjMwNn0.dTOgZ36sdYmdpLywpDlYtOgceL-LWD-5xjIOKHuFsyw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});